[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "text/javascript"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200